### ISSUE TITLE
Bug with 'This action is unauthorized'

### ISSUE THREAD

**Issue by mal1k** [codebarista/nova-webauthn#1]
After following the step-by-step instructions - I see a problem 
**"message": "This action is unauthorized."** 

```
Route: https://*/webauthn/register/options
Method: POST
Payload: empty
```

Maybe I missed something?

![image](https://github.com/user-attachments/assets/14f31881-8cbc-47bd-b1fe-63b46ac3d4e4)

**Comment by codebarista** [comment]
Hi Alex,

the implementation follows a Laravel standard installation and its user model. Have you added the `WebAuthnAuthentication` trait to your User Model [as described  in step 3](https://github.com/codebarista/nova-webauthn?tab=readme-ov-file#3-implementation)? This should authorize the current user for the option request.

```php
namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Laragear\Webauthn\Contracts\WebAuthnAuthenticatable;
use Laragear\Webauthn\WebAuthnAuthentication;

class User extends Authenticatable implements WebAuthnAuthenticatable
{
    use WebAuthnAuthentication;

    // ...
}
```

**Comment by mal1k** [comment]
> Have you added the `WebAuthnAuthentication`

Yes, I have...
![image](https://github.com/user-attachments/assets/a1789bc9-3f83-4029-8b10-094407b28c37)

**Comment by codebarista** [comment]
The User class must also implement `WebAuthnAuthenticatable`:
```php
...
use Laragear\Webauthn\Contracts\WebAuthnAuthenticatable;

class User extends Authenticatable implements WebAuthnAuthenticatable
...
```
